services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rutas_db
    volumes:
      - ./init-mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
  redis:
    image: redis:latest
    container_name: redis
    ports:
        - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  java-app:
    image: rutas-mongo-redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_SERVER_PORT=8080
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=rutas_db
    depends_on:
      - redis
      - mongo
    ports:
        - "8080:8080"

